services:
    
    vote.topic_service:
        class: Arquematics\WallBundle\Topic\VoteTopic
        arguments: 
            - '@gos_web_socket.websocket.client_manipulator'
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: gos_web_socket.topic }
            
    message.topic_service:
        class: Arquematics\WallBundle\Topic\MessageTopic
        arguments: 
            - '@gos_web_socket.websocket.client_manipulator'
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: gos_web_socket.topic }
            
    comment.topic_service:
        class: Arquematics\WallBundle\Topic\CommentTopic
        arguments: 
            - '@gos_web_socket.websocket.client_manipulator'
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: gos_web_socket.topic }
    
    user.publish.listener:
        class: Arquematics\WallBundle\Listener\UserPostPersist
        arguments: ['@session']
        tags:
            - { name: doctrine.event_listener, event: postPersist }
            
    message.publish.listener:
        class: Arquematics\WallBundle\Listener\WallMessagePostPersist
        arguments: ['@session']
        tags:
            - { name: doctrine.event_listener, event: postPersist }
    
    custom.event.facebook_publish:
        class: Arquematics\WallBundle\Listener\SocialFacebook
        arguments: [ '@service_container', '@doctrine.orm.entity_manager']
        tags:
            - { name: kernel.event_listener, event: custom.event.facebook_publish_event, method: onPublish }
    
    custom.event.facebook_unpublish:
        class: Arquematics\WallBundle\Listener\SocialFacebook
        arguments: [ '@service_container', '@doctrine.orm.entity_manager']
        tags:
            - { name: kernel.event_listener, event: custom.event.facebook_un_publish_event, method: onDestroy }
  
    custom.event.twitter_publish:
        class: Arquematics\WallBundle\Listener\SocialTwitter
        arguments: [ '@service_container', '@doctrine.orm.entity_manager']
        tags:
            - { name: kernel.event_listener, event: custom.event.twitter_publish_event, method: onPublish }
    
    custom.event.twitter_unpublish:
        class: Arquematics\WallBundle\Listener\SocialTwitter
        arguments: [ '@service_container', '@doctrine.orm.entity_manager']
        tags:
            - { name: kernel.event_listener, event: custom.event.twitter_un_publish_event, method: onDestroy }
            
    custom.event.linkedin_publish:
        class: Arquematics\WallBundle\Listener\SocialLinkedin
        arguments: [ '@service_container', '@doctrine.orm.entity_manager']
        tags:
            - { name: kernel.event_listener, event: custom.event.linkedin_publish_event, method: onPublish }
    
    custom.event.linkedin_unpublish:
        class: Arquematics\WallBundle\Listener\SocialLinkedin
        arguments: [ '@service_container', '@doctrine.orm.entity_manager']
        tags:
            - { name: kernel.event_listener, event: custom.event.linkedin_un_publish_event, method: onDestroy }