<?php

namespace Arquematics\WallBundle\Entity;

use Doctrine\ORM\EntityRepository;

use Doctrine\ORM\Tools\Pagination\Paginator;

use Arquematics\UserBundle\Entity\UserFriend;

/**
 * Notification repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArFileEncRepository extends EntityRepository
{
    public function findByArFileUser( $arFile, $user)
    {
          $query = $this->getEntityManager()
                ->createQuery("
                    SELECT me
                    FROM WallBundle:ArFileEnc me
                    WHERE ((me.user = :user) AND (me.arFile = :arFile))
                ")
                ->setParameter('user', $user)
                ->setParameter('arFile', $arFile)
        ;
          
        return $query->getOneOrNullResult();
    }
}
