<?php

namespace Arquematics\WallBundle\Entity;

use Doctrine\ORM\EntityRepository;

use Doctrine\ORM\Tools\Pagination\Paginator;

use Arquematics\UserBundle\Entity\UserFriend;

/**
 * Notification repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WallTagEncRepository extends EntityRepository
{
   public function findByTagAndUser( $tag, $user )
   {
        $query = $this->getEntityManager()
                ->createQuery("
                    SELECT me
                    FROM WallBundle:WallTagEnc me
                    LEFT JOIN me.wallTag t
                    WHERE ((me.user = :user) AND (t = :tag))
                ")
                ->setParameter('user', $user)
                ->setParameter('tag', $tag)
        ;
          
        return $query->getOneOrNullResult();
   }
    
   public function findByTagIdUser( $wallTagId, $user)
   {
          $query = $this->getEntityManager()
                ->createQuery("
                    SELECT me
                    FROM WallBundle:WallTagEnc me
                    LEFT JOIN me.wallTag t
                    WHERE ((me.user = :user) AND (t.id = :wallTagId))
                ")
                ->setParameter('user', $user)
                ->setParameter('wallTagId', $wallTagId)
        ;
          
        return $query->getOneOrNullResult();
   }
}
