<?php

namespace Arquematics\WallBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Notification repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WallLinkEncRepository extends EntityRepository
{
    public function findByLinkUser( $wallLink, $user)
    {
          $query = $this->getEntityManager()
                ->createQuery("
                    SELECT me
                    FROM WallBundle:WallLinkEnc me
                    WHERE ((me.user = :user) AND (me.wallLink = :wallLink))
                ")
                ->setParameter('user', $user)
                ->setParameter('wallLink', $wallLink)
        ;
          
        return $query->getOneOrNullResult();
    }
}
