<?php

namespace Arquematics\WallBundle\Entity;

use Doctrine\ORM\EntityRepository;

use Doctrine\ORM\Tools\Pagination\Paginator;

use Arquematics\UserBundle\Entity\UserFriend;

/**
 * Notification repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WallCommentEncRepository extends EntityRepository
{
    public function findByCommentUser( $wallComment, $user)
    {
          $query = $this->getEntityManager()
                ->createQuery("
                    SELECT me
                    FROM WallBundle:WallCommentEnc me
                    WHERE ((me.user = :user) AND (me.comment = :wallcomment))
                ")
                ->setParameter('user', $user)
                ->setParameter('wallcomment', $wallComment)
        ;
          
        return $query->getOneOrNullResult();
    }
    
    public function findByComment( $wallComment)
    {
          $query = $this->getEntityManager()
                ->createQuery("
                    SELECT me
                    FROM WallBundle:WallCommentEnc me
                    WHERE (me.comment = :wallcomment)
                ")
                ->setParameter('wallcomment', $wallComment)
        ;
          
        return $query->getResult();
    }
}
