<?php

namespace Arquematics\WallBundle\Entity;

use Doctrine\ORM\EntityRepository;

use Doctrine\ORM\Tools\Pagination\Paginator;

use Arquematics\UserBundle\Entity\UserFriend;

/**
 * Notification repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WallMessageEncRepository extends EntityRepository
{
    public function findByMenssageUser( $wallMessage, $user)
    {
          $query = $this->getEntityManager()
                ->createQuery("
                    SELECT me
                    FROM WallBundle:WallMessageEnc me
                    WHERE ((me.user = :user) AND (me.wallMessage = :wallMessage))
                ")
                ->setParameter('user', $user)
                ->setParameter('wallMessage', $wallMessage)
        ;
          
        return $query->getOneOrNullResult();
    }
    
    public function findByMenssage($wallMessage)
    {
        $query = $this->getEntityManager()
                ->createQuery("
                    SELECT me
                    FROM WallBundle:WallMessageEnc me
                    WHERE (me.wallMessage = :wallMessage)
                ")
                ->setParameter('wallMessage', $wallMessage)
        ;
        return $query->getResult();
    }
}
